### ISSUE TITLE
User duplicates/hides/deletes Column group

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2-page-builder#595]
As a Marketer I want to duplicate, hide and delete Columns **so that** I can manipulate Column group the same way as other content types and have unified experience

**Preconditions**
* User is logged into Admin Panel
* User is on a page that has Page Builder
* User has Column group on Stage

**Acceptance Criteria**
* User accesses Column group option panel and sees options to duplicate, hide and delete Column group
* User can delete Column group and see all the content inside the Column group deleted. Confirmation message displayed.
* User can delete columns from the Column group except last one. If user wants to delete the last column, the entire group should be deleted PB-1174
  * "trash" icon shown as inactive for the last one column(children) user can click remove only whole Column Group
* User can duplicate Column group with all the content that is inside and see the duplicated Column group appeared under the original Column group.
* User can hide Column group with all the content that is inside, see them blocked from editing on stage and not visible on storefront

**Comment by paras89** [comment]
@magento I am working on this
