### ISSUE TITLE
Page Builder missing support for remote storage / resize image

### ISSUE THREAD

**Issue by in-session** [magento/magento2-page-builder#767]
With the launch of Page Builder 2.4.3 for CE, I still wonder why no resizer for the images has been implemented yet :-) 
Also for the use of Adobe Stock images it would be really useful to integrate this in the core. 
Although the images can be selected from the gallery, also for the mobile display, but the setting of the image size in the frontend are not possible. 

_____
Remote Storage:

Currently there is the problem that you can not use the resize function with remote storage and the pagebuilder.
For the converting of the images there should be a possibility to add parameters to resize the images.

Magento 2.4.3
https://devdocs.magento.com/guides/v2.4/config-guide/remote-storage/config-remote-storage-image-resize.html

_____
Resize Function:

Here it would be very helpful if at least the width of the image can be specified and the image is then reduced in the format and output in the frontend resized:

![Ashampoo_Snap_Montag, 23  August 2021_08h03m16s_020_](https://user-images.githubusercontent.com/16542619/130398186-34739894-d6d4-4885-8316-1a6edbd56591.png)

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance
