### ISSUE TITLE
fix the container for description inserted with page builder inside catalog product view

### ISSUE THREAD

**Issue by PierW** [magento/magento2-page-builder#801]
### Preconditions (*)

1. Magento 2.4.3-p1
2. Module Page Builder Enabled (Default)
3. Design Page - Template Product full width (Default with page builder enabled)

### Steps to reproduce (*)

1. Enter to the backoffice
2. Create a Product and insert a description with page builder inside a row and 1 column
3. Save

### Expected result (*)

1. <img width="1348" alt="Schermata 2022-02-19 alle 20 39 30" src="https://user-images.githubusercontent.com/6259010/154819430-7a130153-375f-46c8-93ef-cc7fff6295f0.png">
2. The text should be aligned

### Actual result (*)

1. <img width="1421" alt="Schermata 2022-02-19 alle 20 35 38" src="https://user-images.githubusercontent.com/6259010/154819499-8d70ddbe-d30f-4470-a489-5710c303db6e.png">

2. It's not aligned

**Comment by PierW** [comment]
@magento I am working on this

**Comment by engcom-Bravo** [comment]
Hi @PierW,

Thanks for your reporting and colloboration.

Similar issue has been confirmed here https://github.com/magento/magento2/issues/35123

Hence We are closing this as a duplicate.

Thanks.
