### ISSUE TITLE
Sabe cms block not possible on Magento 2.4.5 last version

### ISSUE THREAD

**Issue by ghost** [magento/magento2-page-builder#828]
### Preconditions (*)

1. Magento 2.4.5 opens source last
2. PageBuilder is enable

### Steps to reproduce (*)

1. Enable PageBuilder
2. Edit and sabe a cms block

### Expected result (*)

1. Edit and save cms block without error

### Actual result (*)

1. Block not saved without error on logs
![image](https://user-images.githubusercontent.com/17496183/185748108-2d778f88-a52d-4e15-90a4-d6336b462c4f.png)

**Comment by ghost** [comment]
Fixed, was related to conflict with header in pub/.htaccess:

Was "Header set X-Frame-Options CROSS-ORIGIN"
After change to
Header set X-Frame-Options SAMEORIGIN
Save block work again.

**Comment by kamzata** [comment]
In my opinion, the header `X-Frame-Options` should be set to **DENY** for security reasons and the Page Builder should be working the same (which it currently doesn't).
