### ISSUE TITLE
Array.from() issue while adding Google Maps with Page Builder

### ISSUE THREAD

**Issue by SvitlanaZakrevska** [magento/magento2-page-builder#861]
Preconditions (*)

1. Magento version - 2.4.4-p6
2. Magento Page Builder version - 2.2.2-p6

Steps to reproduce (*)
1. In admin panel add a new block or edit an existing one
2. Add a Map from Media Tab

Expected result (*)
Map is displayed:
![Screenshot from 2024-01-12 18-24-44](https://github.com/magento/magento2-page-builder/assets/74734841/748b7c46-94ef-40dd-8eb2-c0766f24bfb4)

Actual result (*)
Error occurs:
![Screenshot from 2024-01-11 23-23-34](https://github.com/magento/magento2-page-builder/assets/74734841/055fc095-66f2-44d4-8ccc-73321404ed8d)
The same is displayed on the website after saving a block where the map should be.

In console there's an error about overriding Array.from() which supposedly conflicts with Prototype.js - https://stackoverflow.com/questions/76955952/array-from-with-an-implementation-that-doesnt-support-iterables-google-maps
Though the error persists after the fix below, the map is visible (see screenshot from expected result section)

After making changes in vendor/magento/module-page-builder/Block/GoogleMapsApi.php:20 from:
`const GOOGLE_MAPS_LIBRARY_URL = 'https://maps.googleapis.com/maps/api/js?v=3&key=%s';`
to:
`const GOOGLE_MAPS_LIBRARY_URL = 'https://maps.googleapis.com/maps/api/js?v=3.53&key=%s';` 
the map is shown

**Comment by engcom-Bravo** [comment]
Hi @SvitlanaZakrevska,

Thanks for your reporting and colloboration.

Similar issue has been confirmed here https://github.com/magento/magento2/issues/38286.

Hence We are closing this as a duplicate.

Thanks.
